
# The name of your workflow, which will appear in the "Actions" tab of your repository.
name: Gemini CLI Actions

# This defines when the workflow will run.
# Here, it runs whenever a comment is created on an issue or pull request.
on:
  issue_comment:
    types: [created]

# This is the "job" that will run. You can give it any name you want.
jobs:
  run-gemini-command:
    # This specifies the type of runner to use.
    runs-on: ubuntu-latest

    # This is a condition that ensures the job only runs if a specific command is used in the comment.
    # It checks if the comment body starts with "@gemini-cli".
    if: startsWith(github.event.comment.body, '@gemini-cli')
    
    # These are the steps the job will execute.
    steps:
      # This step checks out your repository code so the CLI can access it.
      - name: Checkout code
        uses: actions/checkout@v3

      # This is the core step that runs the Gemini CLI.
      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v1
        with:
          # Your Gemini API key, stored securely as a repository secret.
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}

          # The command to pass to the Gemini CLI.
          # Here, it takes the full body of the comment as the command.
          command: ${{ github.event.comment.body }}
