[build]
  publish = "dist"
  command = "npm run build"
  # Only deploy from main; skip Netlify builds for all other branches
  # Netlify skips the build when this command exits 0; non-zero proceeds
  ignore = "if [ \"$BRANCH\" != \"main\" ]; then echo 'Skipping Netlify build for non-main branch: ' \"$BRANCH\"; exit 0; else exit 1; fi"

[build.environment]
  NODE_VERSION = "20.11.1"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Development redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "0"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https://*.supabase.co https://*.supabase.in; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"

# Avoid stale HTML (homepage and other pages)
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

# Force-refresh Astro built assets (CSS/JS) to avoid mixed old/new HTML/CSS
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
