[build]
  publish = "dist"
  command = "npm run build"

# Build optimization: Only trigger builds for relevant file changes
[build.ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!*.md' ':!docs/' ':!README*' ':!CHANGELOG*' ':!LICENSE*' ':!.github/workflows/' ':!scripts/' ':!security-*' ':!audit-reports/' ':!backups/' ':!issues/'"

[build.environment]
  NODE_VERSION = "20.19.4"
  # Enable Netlify build cache
  NETLIFY_CACHE_NODE_MODULES = "true"
  # Skip Chromium download for faster builds  
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

# Build plugins for optimization
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    # Cache node_modules for faster builds
    paths = ["node_modules", ".npm"]
    
[[plugins]]
  package = "netlify-plugin-inline-critical-css"

# Environment variables for Supabase integration
[context.production.environment]
  SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  SUPABASE_PUBLIC_API_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  SUPABASE_SERVICE_ROLE_KEY = "sb_service_role_key_placeholder_for_faq_clicks"
  
  # Frontend environment variables (PUBLIC_ and VITE_ prefixes for client-side access)
  PUBLIC_SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  VITE_SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  
  # SendGrid credentials for email responses
  SENDGRID_API_KEY = "sendgrid_api_key_placeholder"
  SENDGRID_FROM = "noreply@lougehrigfanclub.com"

[context.deploy-preview.environment]
  SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  SUPABASE_PUBLIC_API_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  SUPABASE_SERVICE_ROLE_KEY = "sb_service_role_key_placeholder_for_faq_clicks"
  
  # Frontend environment variables (PUBLIC_ and VITE_ prefixes for client-side access)
  PUBLIC_SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  VITE_SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  
  # SendGrid credentials for email responses
  SENDGRID_API_KEY = "sendgrid_api_key_placeholder"
  SENDGRID_FROM = "noreply@lougehrigfanclub.com"

[context.branch-deploy.environment]
  SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  SUPABASE_PUBLIC_API_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  SUPABASE_SERVICE_ROLE_KEY = "sb_service_role_key_placeholder_for_faq_clicks"
  
  # Frontend environment variables (PUBLIC_ and VITE_ prefixes for client-side access)
  PUBLIC_SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  VITE_SUPABASE_URL = "https://vkwhrbjkdznncjkzkiuo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_Ujfa9-Q184jwhMXRHt3NFQ_DGXvAcDs"
  
  # SendGrid credentials for email responses
  SENDGRID_API_KEY = "sendgrid_api_key_placeholder"
  SENDGRID_FROM = "noreply@lougehrigfanclub.com"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# API redirects (applies to all environments - development and production)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Supabase Edge Functions proxy
[[redirects]]
  from = "/supabase/functions/*"
  to = "https://vkwhrbjkdznncjkzkiuo.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "lougehrigfanclub.com"}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "0"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https://*.supabase.co https://*.supabase.in https://vkwhrbjkdznncjkzkiuo.supabase.co; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"

# Avoid stale HTML (homepage and other pages)
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

# Force-refresh Astro built assets (CSS/JS) to avoid mixed old/new HTML/CSS
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

# Supabase function headers
[[headers]]
  for = "/supabase/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey"
