name: auto/open-pr

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Open or reuse PR to main
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const head = context.ref.replace('refs/heads/', '');
            const base = 'main';
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${head}`, base
            });
            if (prs.length) {
              core.info(`PR already exists: #${prs[0].number}`);
              return;
            }
            const title = `Auto PR: ${head}`;
            const body = `Opened automatically from branch \`${head}\` → \`${base}\`.`;
            const { data: pr } = await github.rest.pulls.create({ owner, repo, head, base, title, body });
            core.info(`Opened PR #${pr.number}`);
