name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate JSON files
        run: npm run validate:json

      - name: Lint
        run: |
          npx eslint .
        continue-on-error: true

      - name: Build
        run: npm run build