---
name: "Dev-Ops: Create Issue"

"on":
  workflow_dispatch:
    inputs:
      title:
        description: "Issue title"
        required: true
        type: string
      body:
        description: "Issue body (Markdown)"
        required: false
        type: string
      labels:
        description: "Comma-separated labels (e.g. bug,priority:high)"
        required: false
        type: string
      assignees:
        description: "Comma-separated assignees (GitHub usernames)"
        required: false
        type: string

permissions:
  contents: read
  issues: write

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v7
        with:
          script: |
            const title = core.getInput('title');
            const body = core.getInput('body') || '';
            const labelsInput = core.getInput('labels') || '';
            const assigneesInput = core.getInput('assignees') || '';

            const labels = labelsInput.split(',').map(s => s.trim())
              .filter(Boolean);
            const assignees = assigneesInput.split(',').map(s => s.trim())
              .filter(Boolean);

            const { owner, repo } = context.repo;
            const { data: issue } = await github.rest.issues.create({
              owner,
              repo,
              title,
              body,
              labels: labels.length ? labels : undefined,
              assignees: assignees.length ? assignees : undefined,
            });

            core.setOutput('issue_number', String(issue.number));
            core.setOutput('issue_url', issue.html_url);

            await core.summary
              .addHeading('Issue created')
              .addLink(issue.title, issue.html_url)
              .write();
