name: Morning Ops Triage (6am New York)

on:
  schedule:
    # 6:00 America/New_York; use two cron entries to cover DST shifts without TZ support
    - cron: '0 10 * * *' # 06:00 EDT (UTC-4)
    - cron: '0 11 * * *' # 06:00 EST (UTC-5)
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  triage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run morning ops triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node scripts/triage_ops_incidents.mjs

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(ops): morning auto-triage updates"
            git push
          else
            echo "No changes to commit."
          fi

