name: Morning Project Issues Sync (6am New York)

on:
  schedule:
    - cron: '0 10 * * *' # 06:00 EDT
    - cron: '0 11 * * *' # 06:00 EST
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sync open project issues to GitHub Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LEAD_ENGINEER_ASSIGNEE: ${{ secrets.LEAD_ENGINEER_ASSIGNEE }}
          OWNER_ASSIGNEE: ${{ secrets.ADMIN }}
        run: node scripts/sync_project_issues.mjs

