name: Morning Project Issues Sync (6am New York)

on:
  schedule:
    - cron: '0 10 * * *' # 06:00 EDT
    - cron: '0 11 * * *' # 06:00 EST
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sync open project issues to GitHub Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LEAD_ENGINEER_ASSIGNEE: ${{ vars.LEAD_ENGINEER_ASSIGNEE }}
          OWNER_ASSIGNEE: ${{ vars.OWNER_ASSIGNEE }}
        run: node scripts/sync_project_issues.mjs

