name: Ops Test: Timeout

on:
  workflow_dispatch:

jobs:
  timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sleep beyond timeout
        timeout-minutes: 1
        run: |
          echo "Simulating a long running step to trigger timeout..."
          sleep 120
