name: search-cron

on:
  schedule:
    - cron: "0 * * * *" # hourly
  workflow_dispatch:

jobs:
  run-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: |
          # Clear npm cache to avoid lockfile issues
          npm cache clean --force
          # Use npm install instead of npm ci for better compatibility
          npm install --no-audit
      - name: Debug environment
        env:
          SUPABASE_PUBLIC_API_KEY: ${{ secrets.SUPABASE_PUBLIC_API_KEY }}
        run: |
          echo "🔍 Search Cron Debug Information"
          echo "================================="
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Environment: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo ""
          echo "📋 Checking required secrets:"
          if [[ -n "$SUPABASE_PUBLIC_API_KEY" ]]; then
            echo "✅ SUPABASE_PUBLIC_API_KEY: Set (length: ${#SUPABASE_PUBLIC_API_KEY})"
          else
            echo "❌ SUPABASE_PUBLIC_API_KEY: Not set"
          fi
          
          if [[ -n "${{ secrets.RSS_FEEDS }}" ]]; then
            echo "✅ RSS_FEEDS: Set"
          else
            echo "⚠️ RSS_FEEDS: Not set (optional)"
          fi
          
          if [[ -n "${{ secrets.NYT_API_KEY }}" ]]; then
            echo "✅ NYT_API_KEY: Set"  
          else
            echo "⚠️ NYT_API_KEY: Not set (optional)"
          fi
          echo ""
          
          # Run the debug script
          node scripts/github_actions_debug.mjs
      - name: Check database migrations
        env:
          SUPABASE_PUBLIC_API_KEY: ${{ secrets.SUPABASE_PUBLIC_API_KEY }}
        continue-on-error: true
        run: |
          echo "🔐 Testing database migrations and connectivity..."
          if node scripts/check_migrations.mjs; then
            echo "✅ Migration check completed successfully"
          else
            echo "❌ Migration check failed - continuing with diagnostics"
          fi
        
      - name: Run diagnostic test
        env:
          SUPABASE_PUBLIC_API_KEY: ${{ secrets.SUPABASE_PUBLIC_API_KEY }}
        continue-on-error: true
        run: |
          echo "🧪 Running diagnostic tests..."
          if node scripts/test_ingest.mjs; then
            echo "✅ Diagnostic test completed successfully"
          else
            echo "❌ Diagnostic test failed - continuing with ingestion attempt"
          fi
        
      - name: Run ingestion (50 max)
        env:
          RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
          NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
          SUPABASE_PUBLIC_API_KEY: ${{ secrets.SUPABASE_PUBLIC_API_KEY }}
        run: |
          echo "📚 Running content ingestion..."
          if node scripts/ingest.mjs "Lou Gehrig" 50; then
            echo "✅ Content ingestion completed successfully"
          else
            echo "❌ Content ingestion failed"
            exit 1
          fi