name: Supabase Daily Schema Backup

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  backup-schema:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create backup directories
        run: |
          mkdir -p backups/daily
          mkdir -p backups/weekly
          mkdir -p backups/monthly
          
      - name: Install Supabase CLI
        run: |
          curl -fsSL https://supabase.com/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Login to Supabase
        run: |
          echo ${{ secrets.SUPABASE_ACCESS_TOKEN }} | supabase login
          
      - name: Link to Supabase project
        run: |
          supabase link --project-ref vkwhrbjkdznncjkzkiuo
          
      - name: Generate schema backup
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          supabase db dump --schema-only --file "backups/daily/schema_backup_${TIMESTAMP}.sql"
          
      - name: Commit and push backup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backups/daily/
          git commit -m "Daily schema backup - $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push
          
      - name: Log completion
        run: echo "Daily schema backup completed at $(date)"