name: Supabase Monthly Full Backup

on:
  schedule:
    # Run monthly on the 1st at 4 AM UTC
    - cron: "0 4 1 * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  backup-full-monthly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create backup directories
        run: |
          mkdir -p backups/daily
          mkdir -p backups/weekly
          mkdir -p backups/monthly
          
      - name: Install Supabase CLI
        run: |
          curl -fsSL https://supabase.com/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Login to Supabase
        run: |
          echo ${{ secrets.SUPABASE_ACCESS_TOKEN }} | supabase login
          
      - name: Link to Supabase project
        run: |
          supabase link --project-ref vkwhrbjkdznncjkzkiuo
          
      - name: Generate full backup
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          supabase db dump --file "backups/monthly/full_backup_${TIMESTAMP}.sql"
          
      - name: Commit and push backup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backups/monthly/
          git commit -m "Monthly full backup - $(date +"%Y-%m-%d")" || echo "No changes to commit"
          git push
          
      - name: Log completion
        run: echo "Monthly full backup completed at $(date)"