name: Traffic Simulator

on:
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  simulate-traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Pure JWT Traffic Simulator
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          echo "🚀 Starting pure JWT traffic simulator..."
          echo "This will keep Supabase project active with pure JWT mode"
          echo "Running for 4 minutes with 10 users"
          
          # Run the pure JWT traffic simulator for 4 minutes
          timeout 240s node lgfc_pure_jwt_traffic_simulator.cjs --interval=30000 --users=10
          
          echo "✅ Pure JWT traffic simulation completed"
          echo "Next run in 5 minutes..."