name: Traffic Simulator

on:
  schedule:
    - cron: "*/5 * * * *"  # Run every 5 minutes
  workflow_dispatch:  # Allow manual trigger

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  simulate-traffic:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Enhanced JWT Traffic Simulator
        run: |
          echo "🚀 Starting enhanced JWT traffic simulator..."
          echo "This will keep Supabase project active with enhanced JWT mode"
          echo "Running for 4 minutes with 15 users (URL pinging + API calls)"
          
          # Run the enhanced JWT traffic simulator for 4 minutes
          timeout 240s node lgfc_enhanced_jwt_traffic_simulator.cjs --interval=30000 --users=15
          
          echo "✅ Enhanced JWT traffic simulation completed"
          echo "Next run in 5 minutes..."